const CHALLENGE = {
  CREATE: {
    FETCH: "CREATE_CHALLENGE_FETCH",
    SUCCESS: "CREATE_CHALLENGE_SUCCESS",
    ERROR: "CREATE_CHALLENGE_ERROR",
  },
  GET_CHALLENGES: {
    FETCH: "GET_CHALLENGES_FETCH",
    SUCCESS: "GET_CHALLENGES_SUCCESS",
    ERROR: "GET_CHALLENGES_ERROR",
  },
  UPLOAD_MEDIA: {
    FETCH: "UPLOAD_MEDIA_FETCH",
    SUCCESS: "UPLOAD_MEDIA_SUCCESS",
    ERROR: "UPLOAD_MEDIA_ERROR",
  },
  GET_CHALLENGE: {
    FETCH: "GET_CHALLENGE_FETCH",
    SUCCESS: "GET_CHALLENGE_SUCCESS",
    ERROR: "GET_CHALLENGE_ERROR",
  },
  INVITE_OBSERVER: "INVITE_OBSERVER",
  UNINVITE_OBSERVER: "UNINVITE_OBSERVER",
  INVITE_CHALLENGER: "INVITE_CHALLENGER",
  UNINVITE_CHALLENGER: "UNINVITE_CHALLENGER",
  INVITE_USERS: {
    FETCH: "INVITE_USERS_FETCH",
    SUCCESS: "INVITE_USERS_SUCCESS",
    ERROR: "INVITE_USERS_ERROR",
  },
};

export default CHALLENGE;
