const CHALLENGE = {
  CREATE: {
    FETCH: "CREATE_CHALLENGE_FETCH",
    SUCCESS: "CREATE_CHALLENGE_SUCCESS",
    ERROR: "CREATE_CHALLENGE_ERROR",
  },
  GET_CHALLENGES: {
    FETCH: "GET_CHALLENGES_FETCH",
    SUCCESS: "GET_CHALLENGES_SUCCESS",
    ERROR: "GET_CHALLENGES_ERROR",
  },
  UPLOAD_MEDIA: {
    FETCH: "UPLOAD_MEDIA_FETCH",
    SUCCESS: "UPLOAD_MEDIA_SUCCESS",
    ERROR: "UPLOAD_MEDIA_ERROR",
  },
};

export default CHALLENGE;
