const USER = {
  SIGN_IN: {
    FETCH: "SIGN_IN_FETCH",
    SUCCESS: "SIGN_IN_SUCCESS",
    ERROR: "SIGN_IN_ERROR",
  },
  SIGN_OUT: {
    FETCH: "SIGN_OUT_FETCH",
    SUCCESS: "SIGN_OUT_SUCCESS",
  },
  SIGN_UP: {
    FETCH: "SIGN_UPT_FETCH",
    SUCCESS: "SIGN_UP_SUCCESS",
  },
  INIT_ADMIN_USER: {
    FETCH: "INIT_ADMIN_USER_FETCH",
    SUCCESS: "INIT_ADMIN_USER_SUCCESS",
    ERROR: "INIT_ADMIN_USER_ERROR",
  },
  GET_PROFILE: {
    FETCH: "GET_PROFILE_FETCH",
    SUCCESS: "GET_PROFILE_SUCCESS",
    ERROR: "GET_PROFILE_ERROR",
  },
};

export default USER;
