export default {
  SIGN_IN: {
    FETCH: 'SIGN_IN_FETCH',
    SUCCESS: 'SIGN_IN_SUCCESS',
    ERROR: 'SIGN_IN_ERROR',
  },
  SIGN_OUT: {
    FETCH: 'SIGN_OUT_FETCH',
    SUCCESS: 'SIGN_OUT_SUCCESS',
  },
  GET_PROFILE: {
    FETCH: 'GET_PROFILE_FETCH',
    SUCCESS: 'GET_PROFILE_SUCCESS',
    ERROR: 'GET_PROFILE_ERROR',
  },
};
